name: Build RustDesk Custom

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      RENDEZVOUS_SERVER: ${{ vars.RENDEZVOUS_SERVER }}
      RELAY_SERVER: ${{ vars.RELAY_SERVER }}
      API_SERVER: ${{ vars.API_SERVER }}
      KEY: ${{ vars.KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Build
        run: cargo build --release

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-custom
          path: target/release/rustdesk.exe
