name: Build RustDesk Custom

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      RENDEZVOUS_SERVER: ${{ vars.RENDEZVOUS_SERVER }}
      RELAY_SERVER: ${{ vars.RELAY_SERVER }}
      API_SERVER: ${{ vars.API_SERVER }}
      KEY: ${{ vars.KEY }}
      VCPKG_ROOT: C:\vcpkg

    steps:
      - name: Checkout (com submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # 🔥 AQUI ESTÁ O QUE FALTAVA
      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg C:\vcpkg
          C:\vcpkg\bootstrap-vcpkg.bat

      - name: Install dependencies
        run: |
          C:\vcpkg\vcpkg install opus:x64-windows

      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo "%USERPROFILE%\.cargo\bin" >> $env:GITHUB_PATH

      - name: Build
        run: cargo build --release

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-custom
          path: target/release/rustdesk.exe
